### ISSUE TITLE
Does grid_sample work for openVINO? 

### ISSUE THREAD

**Issue by SamitHuang** [dkurt/openvino_pytorch_layers#15]
Thanks for your sharing! As it grid_sample is not mentioned in README, I wonder whether it works for openVINO custom layer?

**Comment by dkurt** [comment]
Hi! Yes, just merged with https://github.com/dkurt/openvino_pytorch_layers/pull/14. Works fone with OpenVINO 2021.2 (forgot to add to README)

**Comment by SamitHuang** [comment]
Thank you so much for the reply. Got it. 

I am working on implementing the Categorical distribution sampling (tf.distributions.categorical or torch.distributions.categorical) for openVINO, which is commonly used in RL models. 

It is so wired that there is no random generation ops in openVINO like random.uniform.  May I ask what is the optimal way for such an implementation? e.g., some c++ math library, intel MKL, or implement it in the front phase.  Appreciate your help and hope to merge it to your repository if I get it done.

**Comment by dkurt** [comment]
@SamitHuang, the thing is that random ops are non-deterministic. You may start with just a reference custom CPU layers (using OpenCV for random array generation, as for example). OpenCV is a part of OpenVINO.

**Comment by SamitHuang** [comment]
Thanks. That's good advice to me. I was thinking about using an external library like gsl_ran_multinomial. Now using uniform distribution sampling in opencv plus intel MKL math library for transforming the uniform dist. to categorical dist. (by gumbel-softmax or binary search) should be more efficient. 

By the way, did you try to use the mkl library when doing the op extension? It would be helpful if there is some examples! 

The RL model is a q-learning model for a game agent, but it is not released on github. I would to like to do so after permission!

**Comment by dkurt** [comment]
> By the way, did you try to use the mkl library when doing the op extension? It would be helpful if there is some examples!

Please take a look at https://github.com/dkurt/openvino_pytorch_layers/pull/13. It's an example with Fast Fourier Transform from MKL.

**Comment by dkurt** [comment]
I think that we can close it
