### ISSUE TITLE
Question about Standalone Operation

### ISSUE THREAD

**Issue by AyanKumarBhunia** [dkurt/openvino_pytorch_layers#38]
Once I convert the PyTorch model to ONNX -- Can I run the converted model (involving grid_sample) standalone without any dependency on this openvino_pytorch_layers package?

**Comment by dkurt** [comment]
Hi! Currently, this repo provides instructions which requires use a Python package:
```python
from openvino_extensions import get_extensions_path
from openvino.inference_engine import IECore

ie = IECore()
ie.add_extension(get_extensions_path(), 'CPU')
```
which can be installed by pip: `pip install openvino-extensions`

If you wanted use it in C++ - you need compile extensions .so library or embed extensions code in runtime.

Especially about grid_sample, probably there is an option to convert models with this operation using existing OpenVINO ops but I have not tried.

**Comment by dkurt** [comment]
@AyanKumarBhunia, which layer is interesting for you?
